
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Contact from '../components/Contact';



export default function Home() {
    return (
      <div>
        <Head>
          <title>SOS Libras</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/../logo.jpeg" />
        </Head>

      <Navbar />    
     
      <About />      
      <Main />
      <Contact />

      
       
      
  
      </div>
    )
  }
  